@startuml clippy
skinparam linetype ortho
class Tenant {
    name
    invoiceAddress
    ...
}
note left: There is only one Tenant\nconnected to the root OrgUnit
class OrgUnit {
    name
    description
    logoUrl
    websiteUrl
    ...
}
class OrgUnitType {
    name
    description
    icon
}
class Location {
    name
    street
    zip
    city
    country
    ...
}
class User {
    name
    email
    phone
    address
    ...
}
note right: What about payed users?\nPayed users are not a\ndifferent entity.
class Shift {
    start
    end
}
class TimeEntry {
    start
    end
    status {started, finished, validated, rejected}
    note ?
}
note right: How do we manage\nstatus and validation?
class Membership {
    role {admin, volunteer}
}
class Role {
    name
    description
}
class Permission {
    key
    description
}
class MembershipRequest {
    status {pending, accepted, rejected}
    reviewedBy
    reviewedAt
    rejectionReason
}
class Assignment {
    status {invited, accepted, rejected}
}
class Review {
    rating
    review
}
class VolunteeringSession {
    status {started, finished, validated, rejected}
    note ?
}
note right: Is this needed?
class ValidationAction {
    note
    moderator
    timestamp
}
note right: How is reject => update\nof a TimeEntry working?

Tenant "1" -- "1" OrgUnit
OrgUnit "*" -left- "1" OrgUnitType
OrgUnit "* child" o-- "1 parent" OrgUnit
OrgUnit "0..1" -- "*" Shift
Assignment "*" -up- "1" User
Shift "1" -up- "*" Assignment
Review "*" -up- "1" User
Shift "1" -up- "*" Review
TimeEntry "*" -up- "1" User
TimeEntry "*" -- "1" Shift
VolunteeringSession "*" -up- "1" User
VolunteeringSession "*" -left- "1" Shift
VolunteeringSession "1" -- "*" TimeEntry
TimeEntry "1" -- "0..1" ValidationAction

OrgUnit "1" -right- "*" Membership
Membership "*" -down- "1" User

OrgUnit "1" -right- "*" MembershipRequest
MembershipRequest "*" -right- "1" User

Location "0..1" -up- "*" OrgUnit
Location "0..1" -right- "*" Shift

Role "*" -right- "*" Permission

Role "*" -- "*" Membership

@enduml