export enum EventInviteStatus {
  INVITED = 'INVITED',
  ACCEPTED = 'ACCEPTED',
  VOLUNTEER_REJECTED = 'VOLUNTEER_REJECTED',
  ADMIN_REJECTED = 'ADMIN_REJECTED',
  CANCELLED = 'CANCELLED',
  SELF_JOINED = 'SELF_JOINED',
}
