export enum EventInviteStatus {
  ADMIN_INVITED = 'ADMIN_INVITED',
  AWAITING_ADMIN_APPROVAL = 'AWAITING_ADMIN_APPROVAL',
  WAITLIST_JOINED = 'WAITLIST_JOINED',
  JOINED = 'JOINED',
  VOLUNTEER_REJECTED = 'VOLUNTEER_REJECTED',
  VOLUNTEER_CANCELLED = 'VOLUNTEER_CANCELLED',
  ADMIN_REJECTED = 'ADMIN_REJECTED',
}
