export enum ReimbursementTypeKey {
  EHRENAMT = 'EHRENAMT',
  UEBUNGSLEITER = 'UEBUNGSLEITER',
}

export enum DocumentKind {
  CONTRACT = 'CONTRACT',
  INVOICE = 'INVOICE',
}

export enum RenewalCadence {
  YEARLY = 'YEARLY',
  MONTHLY = 'MONTHLY',
}

export enum SigneeType {
  VOLUNTEER = 'VOLUNTEER',
  PERMISSION_HOLDER = 'PERMISSION_HOLDER',
}

export enum ContractStatus {
  AWAITING_VOLUNTEER_SIGNATURE = 'AWAITING_VOLUNTEER_SIGNATURE',
  AWAITING_NGO_SIGNATURE = 'AWAITING_NGO_SIGNATURE',
  ACTIVE = 'ACTIVE',
  EXPIRED = 'EXPIRED',
  DECLINED = 'DECLINED',
}

export enum InvoiceStatus {
  AWAITING_VOLUNTEER_SIGNATURE = 'AWAITING_VOLUNTEER_SIGNATURE',
  AWAITING_SUPERVISOR_SIGNATURE = 'AWAITING_SUPERVISOR_SIGNATURE',
  READY = 'READY',
  DECLINED = 'DECLINED',
}

export enum DocumentStatusChange {
  CREATED = 'CREATED',
  SIGNED = 'SIGNED',
  COUNTERSIGNED = 'COUNTERSIGNED',
  ACTIVATED = 'ACTIVATED',
  DECLINED = 'DECLINED',
  EXPIRED = 'EXPIRED',
}
