@startuml clippy
class Organisation {
    name
    invoiceAddress
    ...
}
note top: There is only one Organisation\nconnected to the root OrgUnit
class OrgUnit {
    name
    description
    ...
}
class OrgUnitType {
    name
    description
    icon
}
class Location {
    name
    street
    zip
    city
    country
    ...
}
package "User & Profile" {
    class User {
        name
        email
        phoneNumber
        address
        bankAccountNumber
        ...
    }
    class OrganisationUserProfile {
        userProfileAccessApproved
        note
        status {pending, active, blacklisted, inactive}
    }
    class IncidentReport {
        description
    }
    class Document {
        name
        mimeType
        storageKey
        uploadedAt
    }
}
package "Operations" {
    class Shift {
        start
        end
    }
    class ShiftAssignment {
        status {invited, accepted, rejected}
    }
    class TimeEntry {
        start
        end
        status {started, finished, validated, rejected}
        note ?
    }
    note bottom: How do we manage\nstatus and validation?\nHow is reject => update\nof a TimeEntry working?
}
class Membership {
}
class Role {
    name
    description
}
class Permission {
    key
    description
}
class MembershipRequest {
    status {pending, accepted, rejected}
    reviewedBy
    reviewedAt
    rejectionReason
}
package RequirementProfiles {
    class RequirementProfile {
        name
        description
    }
    class Requirement {
        type {document, check, date, ...}
        name
        description
        mandatory
    }
    class RequirementProfileSubmission {
        status {draft, submitted, approved, rejected}
        submittedAt
        reviewedAt
        reviewedBy
    }
    interface RequirementFulfillment {
        type: string
        value: string
        status {draft, submitted, approved, rejected}
        submittedAt
        reviewedAt
        reviewedBy
    }
    class RequirementFulfillmentUpload {
    }
    class RequirementFulfillmentCheck {
    }
    class RequirementFulfillmentText {
    }
    class RequirementFulfillmentDate {
    }
}



Organisation [root] "1" -- "1" OrgUnit
OrgUnit "*" -up- "1" OrgUnitType : "categorized by >"
OrgUnit "*\nchild" o-- "1\nparent" OrgUnit

OrgUnit "1" -- "*" Membership
Membership "*" -- "1" User

Organisation "1" -- "*" OrganisationUserProfile : "owns >"
OrganisationUserProfile "*" -- "1" User

OrgUnit "1" -- "*" MembershipRequest : "receives >"
MembershipRequest "*" -- "1" User : "submitted by >"

OrgUnit "*" -- "0..1" Location : "is at >"
Location "0..1" -- "*" Shift : "is at <"

Role "*" -left- "*" Permission : "groups >"
Role "*" -- "*" Membership
Organisation "1" -- "*" Role : "defines >"

OrgUnit "*" -- "*" RequirementProfile : "mark as favorite >"
Organisation "1" -- "*" RequirementProfile : "defines >"
Organisation "1" -- "*" Requirement : "defines >"
RequirementProfile "*" -right- "*" Requirement : "groups >"
User "1" -up- "*" Document : "owns >"
RequirementFulfillmentUpload "*" -- "0..1" Document : "backed by >"
Membership "0..1" -right- "*" RequirementProfileSubmission
RequirementProfileSubmission "*" -right- "*" RequirementFulfillment
MembershipRequest "0..1" -- "*" RequirementProfileSubmission
RequirementProfileSubmission "*" -up- "1" RequirementProfile : "fulfills >"
RequirementFulfillment "*" -up- "1" Requirement : "fulfills >"
RequirementFulfillment "*" -- "1" OrganisationUserProfile : "store for reuse <"
RequirementFulfillmentUpload .up.|> RequirementFulfillment
RequirementFulfillmentCheck .up.|> RequirementFulfillment
RequirementFulfillmentText .up.|> RequirementFulfillment
RequirementFulfillmentDate .up.|> RequirementFulfillment

OrganisationUserProfile "1" -- "*" IncidentReport
IncidentReport "*" -right- "1" User : "reported by >"

OrgUnit "0..1" -- "*" Shift
User "1" -- "*" ShiftAssignment
Shift "1" -- "*" ShiftAssignment
User "1" -- "*" TimeEntry
TimeEntry "*" -- "1" Shift : "logged against >"

@enduml