export enum MembershipRequestStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum JoinOrganizationStatus {
  JOINED = 'JOINED',
  MEMBERSHIP_REQUESTED = 'MEMBERSHIP_REQUESTED',
  REQUIREMENTS_NEEDED = 'REQUIREMENTS_NEEDED',
}
